
ce_set(PAL_EXECUTABLE_APPLICATION_FLAG MACOSX_BUNDLE)

ce_set(PAL_TRAIT_BUILD_EDITOR TRUE)

# Set the deployment target for MacOS
set(CE_MAC_DEPLOYMENT_TARGET "11.0" CACHE STRING "Mac Deployment Target")
set(CMAKE_OSX_DEPLOYMENT_TARGET ${CE_MAC_DEPLOYMENT_TARGET})

ce_set(CMAKE_OSX_ARCHITECTURES "universal")

